# Generated by Django 3.2.16 on 2022-11-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='snippet',
            field=models.TextField(null=True),
        ),
    ]
