# Generated by Django 3.2.16 on 2022-11-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_messages', '0003_errorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='status_code',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
